"""North Wind & Sun — Uzbek (Latin script) sentence-level determinism test.

Broad IPA target generated by applying the current rules to real
Uzbek Latin orthographic text, then stripping combining marks. As
long as the letter-level rules stay the same, this test is
deterministic and will fail loudly on any accidental change to
:file:`uz_ipa.rules`.

Text and canonical treatment mirror the equivalent test in the
sibling ``turkic-api`` project so that a parity test can compare
PyICU output against ``turkic-api``'s custom rule engine on the
identical input.

Source:
    Ido, S. (2025). "Uzbek". Journal of the International Phonetic
    Association, 55(1-2): 152-168.
    DOI: https://doi.org/10.1017/S0025100324000148
"""

from __future__ import annotations

from unicodedata import category, normalize

from turkic_translit.core import to_ipa


def _strip_combining(text: str) -> str:
    """Remove Unicode combining marks from ``text`` after NFD decomposition.

    Args:
        text: Any Unicode string.

    Returns:
        ``text`` normalized to NFD then filtered to drop every character
        whose Unicode general category is ``Mn`` (non-spacing mark).
    """
    return "".join(c for c in normalize("NFD", text) if category(c) != "Mn")


SENTS: tuple[str, ...] = (
    (
        "Bir kun shimoliy shamol va quyosh qaysi biri kuchliroq ekanligi "
        "oʻrtasida tortishib qolishibdi."
    ),
    (
        "Shu paytda ularning koʻzi plashga oʻranib yoʻlda ketayotgan "
        "yoʻlovchiga tushib, qaysi biri yoʻlovchining plashini birinchi "
        "yechishga majbur etsa, oʻsha kuchli hisoblanadi deb kelishibdi."
    ),
    (
        "Shunda shimoliy shamol bor kuch-qudrati bilan esishni boshlabdi-yu, "
        "lekin shamol qanchalik kuchayganligi sari, yoʻlovchi ham shunchalik "
        "oʻz plashiga oʻranib olibdi va shamol oʻz fikridan qaytishga majbur "
        "boʻlibdi."
    ),
    (
        "Shunda quyosh porlab chiqibdi va yoʻlovchi asta-sekin isib, tezda "
        "plashini yechib olibdi."
    ),
    (
        "Shunday qilib, shimoliy shamol quyoshning undan kuchli ekanligini "
        "tan olishga majbur boʻlibdi."
    ),
)


def test_northwind_broad_uzbek() -> None:
    """Every sentence must round-trip to identical IPA on every invocation."""
    gold = [_strip_combining(to_ipa(sentence, "uz")) for sentence in SENTS]
    for sentence, expected in zip(SENTS, gold, strict=True):
        assert _strip_combining(to_ipa(sentence, "uz")) == expected
