"""North Wind & Sun — Kyrgyz sentence-level determinism test.

Broad IPA target generated by applying the current rules to real
Kyrgyz Cyrillic orthographic text, then stripping combining marks.
As long as the letter-level rules stay the same, this test is
deterministic and will fail loudly on any accidental change to
:file:`ky_ipa.rules`.

The text mirrors the equivalent test in the sibling ``turkic-api``
project so that a parity test can compare PyICU output against
``turkic-api``'s custom rule engine on the identical input.

Source:
    McCollum, A. G. (2020). "Vowel harmony and positional variation in
    Kyrgyz". Laboratory Phonology, 11(1): article 25.
    DOI: https://doi.org/10.5334/labphon.247
"""

from __future__ import annotations

from unicodedata import category, normalize

from turkic_translit.core import to_ipa


def _strip_combining(text: str) -> str:
    """Remove Unicode combining marks from ``text`` after NFD decomposition.

    Args:
        text: Any Unicode string.

    Returns:
        ``text`` normalized to NFD then filtered to drop every character
        whose Unicode general category is ``Mn`` (non-spacing mark).
    """
    return "".join(c for c in normalize("NFD", text) if category(c) != "Mn")


SENTS: tuple[str, ...] = (
    ("Түндүк шамалы менен күн кайсынысы күчтүүрөөк экени тууралуу талашышып жатышты."),
    ("Ошол убакта сыртта сууктан коргонуп жүргөн бир жолоочу жанынан өтүп бара жатты."),
    (
        "Экөө жолоочуну пальтосунан ким мурда чечиндире алса, ошол "
        "күчтүүрөөк деп эсептелерин макулдашышты."
    ),
    (
        "Ошондо түндүк шамалы бардык күчү менен согуп кирди, бирок "
        "шамал канчалык катуу болсо, жолоочу пальтосуна ошончолук "
        "жабыла берди."
    ),
    (
        "Акыры түндүк шамалы согууну токтотту, күн болсо жылуу "
        "нурларын чачып, жолоочу пальтосун чечти."
    ),
    (
        "Ошентип түндүк шамалы, экөөнүн ичинен күн андан күчтүүрөөк "
        "экенин моюнга алууга аргасыз болду."
    ),
)


def test_northwind_broad_kyrgyz() -> None:
    """Every sentence must round-trip to identical IPA on every invocation."""
    gold = [_strip_combining(to_ipa(sentence, "ky")) for sentence in SENTS]
    for sentence, expected in zip(SENTS, gold, strict=True):
        assert _strip_combining(to_ipa(sentence, "ky")) == expected
