"""Maamme — Finnish sentence-level determinism test.

Broad IPA target generated by applying the current rules to the first
stanza of Runeberg's *Maamme* (the Finnish national anthem, 1848),
then stripping combining marks. As long as the letter-level rules
stay the same, this test is deterministic and will fail loudly on any
accidental change to :file:`fi_ipa.rules`.

Text and canonical treatment mirror the equivalent test in the
sibling ``turkic-api`` project so that a parity test can compare
PyICU output against ``turkic-api``'s custom rule engine on the
identical input.

Source:
    Suomi, K., Toivanen, J., & Ylitalo, R. (2008). Finnish sound
    structure: Phonetics, phonology, phonotactics and prosody.
    Studia Humaniora Ouluensia 9. Oulu: Oulu University Press.
    ISBN: 978-951-42-8984-2
    URN: https://urn.fi/URN:ISBN:9789514289842
"""

from __future__ import annotations

from unicodedata import category, normalize

from turkic_translit.core import to_ipa


def _strip_combining(text: str) -> str:
    """Remove Unicode combining marks from ``text`` after NFD decomposition.

    Args:
        text: Any Unicode string.

    Returns:
        ``text`` normalized to NFD then filtered to drop every character
        whose Unicode general category is ``Mn`` (non-spacing mark).
    """
    return "".join(c for c in normalize("NFD", text) if category(c) != "Mn")


LINES: tuple[str, ...] = (
    "Oi maamme, Suomi, synnyinmaa,",
    "soi, sana kultainen!",
    "Ei laaksoa, ei kukkulaa,",
    "ei vettä rantaa rakkaampaa,",
    "kuin kotimaa tää pohjoinen,",
    "maa kallis isien!",
)


def test_maamme_broad_finnish() -> None:
    """Every line must round-trip to identical IPA on every invocation."""
    gold = [_strip_combining(to_ipa(line, "fi")) for line in LINES]
    for line, expected in zip(LINES, gold, strict=True):
        assert _strip_combining(to_ipa(line, "fi")) == expected
