"""North Wind & Sun — Uyghur sentence-level determinism test.

Broad IPA target generated by applying the current rules to real
Uyghur Arabic-script orthographic text, then stripping combining
marks. As long as the letter-level rules stay the same, this test
is deterministic and will fail loudly on any accidental change to
:file:`ug_ipa.rules`.

The text mirrors the equivalent test in the sibling ``turkic-api``
project so that a parity test can compare PyICU output against
``turkic-api``'s custom rule engine on the identical input.

Source:
    McCollum, A. G. (2021). "Transparency, locality, and contrast in
    Uyghur backness harmony". Laboratory Phonology, 12(1): article 8.
    DOI: https://doi.org/10.5334/labphon.239
"""

from __future__ import annotations

from unicodedata import category, normalize

from turkic_translit.core import to_ipa


def _strip_combining(text: str) -> str:
    """Remove Unicode combining marks from ``text`` after NFD decomposition.

    Args:
        text: Any Unicode string.

    Returns:
        ``text`` normalized to NFD then filtered to drop every character
        whose Unicode general category is ``Mn`` (non-spacing mark).
    """
    return "".join(c for c in normalize("NFD", text) if category(c) != "Mn")


SENTS: tuple[str, ...] = (
    ("شىمالىي شامال بىلەن قۇياش ئۆزئارا كۈچلۈك دەپ تالىشىۋاتاتتى."),
    ("شۇ چاغدا قېلىن پالتوغا ئورانغان بىر يولۇچى ئۇلارنىڭ يېنىدىن ئۆتۈپ كەتتى."),
    (
        "ئۇلار كېلىشتىكى، يولۇچىنىڭ پالتوسىنى كىم ئالدىنقى بولۇپ "
        "سالدۇرۇۋالسا شۇنىڭ كۈچلۈك سانالغانلىقى ئۈچۈن دەپ."
    ),
    (
        "شۇنىڭ بىلەن شىمالىي شامال بار كۈچى بىلەن چاچرىۋاتاتتى، "
        "لېكىن قانچە كۈچلۈك چاچرىسا يولۇچى پالتوسىغا شۇنچە قاتتىق ئورىنىۋالدى."
    ),
    (
        "ئاخىرىدا شىمالىي شامال چاچرىشتىن توختاپ قالدى، ئاندىن "
        "قۇياش ئىسسىق نۇرلىرىنى چاچتى ۋە يولۇچى پالتوسىنى ساقىتتى."
    ),
    (
        "شۇنىڭ بىلەن شىمالىي شامال قۇياشنىڭ ئۆزىدىن كۈچلۈك ئىكەنلىكىنى "
        "ئېتىراپ قىلىشقا مەجبۇر بولدى."
    ),
)


def test_northwind_broad_uyghur() -> None:
    """Every sentence must round-trip to identical IPA on every invocation."""
    gold = [_strip_combining(to_ipa(sentence, "ug")) for sentence in SENTS]
    for sentence, expected in zip(SENTS, gold, strict=True):
        assert _strip_combining(to_ipa(sentence, "ug")) == expected
