"""North Wind & Sun — Azerbaijani sentence-level determinism test.

Broad IPA target generated by applying the current rules to real
Azerbaijani orthographic text, then stripping combining marks. As long
as the letter-level rules stay the same, this test is deterministic
and will fail loudly on any accidental change to :file:`az_ipa.rules`.

Text and canonical treatment mirror the equivalent test in the
sibling ``turkic-api`` project so that a parity test can compare
PyICU output against ``turkic-api``'s custom rule engine on the
identical input.

Source:
    Ghaffarvand Mokari, P. & Werner, S. (2017). "Azerbaijani".
    Journal of the International Phonetic Association, 47(2): 207-212.
    DOI: https://doi.org/10.1017/S0025100317000184
"""

from __future__ import annotations

from unicodedata import category, normalize

from turkic_translit.core import to_ipa


def _strip_combining(text: str) -> str:
    """Remove Unicode combining marks from ``text`` after NFD decomposition.

    Args:
        text: Any Unicode string.

    Returns:
        ``text`` normalized to NFD then filtered to drop every character
        whose Unicode general category is ``Mn`` (non-spacing mark).
    """
    return "".join(c for c in normalize("NFD", text) if category(c) != "Mn")


SENTS: tuple[str, ...] = (
    "Şimal yeli ilə Günəş mübahisə edirdilər ki, hansı daha güclüdür.",
    "O zaman bir isti əbaya bürünmüş səyahətçi oradan keçirdi.",
    (
        "Belə anlaşdılar ki, hər hansı əvvəldə bəcərdi səyahətçinin əbasını "
        "çıxarda, o birisindən daha güclüdür."
    ),
    "O zaman Şimal yeli bəcərdiyi qədər əsməyə başladı.",
    "Amma hər nə qədər artıq əsdikcə, səyahətçi də əbasını dərəsinə bürüyürdü.",
    "Sonda Şimal yeli əsməyi buraxdı.",
    ("Sonra Günəş isti şəfəqlənməyə başladı və bilavasitə səyahətçi əbasını çıxartdı."),
    (
        "Və Şimal yeli məcbur oldu etiraf eliyə ki, Günəş ikisinin arasında "
        "daha güclüdür."
    ),
)


def test_northwind_broad_azerbaijani() -> None:
    """Every sentence must round-trip to identical IPA on every invocation."""
    gold = [_strip_combining(to_ipa(sentence, "az")) for sentence in SENTS]
    for sentence, expected in zip(SENTS, gold, strict=True):
        assert _strip_combining(to_ipa(sentence, "az")) == expected
