"""North Wind & Sun — Turkish sentence-level determinism test.

Broad IPA target generated by applying the current rules to real
Turkish orthographic text, then stripping combining marks. As long
as the letter-level rules stay the same, this test is deterministic
and will fail loudly on any accidental change to :file:`tr_ipa.rules`.

The text mirrors the equivalent test in the sibling ``turkic-api``
project so that a parity test can compare PyICU output against
``turkic-api``'s custom rule engine on the identical input.

Source:
    Zimmer, K. & Orgun, O. (1992). "Turkish". Journal of the
    International Phonetic Association, 22(1-2): 43-45.
    DOI: https://doi.org/10.1017/S0025100300004588
"""

from __future__ import annotations

from unicodedata import category, normalize

from turkic_translit.core import to_ipa


def _strip_combining(text: str) -> str:
    """Remove Unicode combining marks from ``text`` after NFD decomposition.

    Args:
        text: Any Unicode string.

    Returns:
        ``text`` normalized to NFD then filtered to drop every character
        whose Unicode general category is ``Mn`` (non-spacing mark).
    """
    return "".join(c for c in normalize("NFD", text) if category(c) != "Mn")


SENTS: tuple[str, ...] = (
    (
        "Kuzey rüzgarı ile güneş, hangisinin daha güçlü olduğu konusunda "
        "tartışıyorlardı."
    ),
    "O sırada oradan sıcak bir paltoya bürünmüş bir yolcu geçmekteydi.",
    (
        "Yolcunun paltosunu ilk çıkartmaya kim başarırsa, onun daha "
        "güçlü sayılacağı konusunda anlaştılar."
    ),
    "Bunun üzerine kuzey rüzgarı olanca gücüyle esmeye başladı.",
    (
        "Ne var ki, rüzgar sertleştikçe yolcu da paltosuna daha çok "
        "sarındı ve sonunda kuzey rüzgarı esmekten vazgeçti."
    ),
    ("Sonra güneş sıcak bir şekilde parladı ve yolcu az sonra paltosunu çıkardı."),
    (
        "Böylece kuzey rüzgarı, güneşin ikisi arasında daha güçlü "
        "olduğunu kabul etmek zorunda kaldı."
    ),
)


def test_northwind_broad_turkish() -> None:
    """Every sentence must round-trip to identical IPA on every invocation."""
    gold = [_strip_combining(to_ipa(sentence, "tr")) for sentence in SENTS]
    for sentence, expected in zip(SENTS, gold, strict=True):
        assert _strip_combining(to_ipa(sentence, "tr")) == expected
